variables:
  DOCKER_TLS_CERTDIR: ""

services:
  - name: docker:20.10.20-dind
    alias: docker
    command: ["--tls=false"]

stages:
  - build

.setup:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  extends: .setup
  stage: build
  image: docker:20.10.20
  script:
    - docker context create multi-arch-builder
    - docker buildx create multi-arch-builder --driver docker-container --use
    - docker buildx inspect --bootstrap
    - docker buildx build --pull
      --cache-from type=registry,ref="$CI_REGISTRY_IMAGE:cache"
      --cache-to type=registry,ref="$CI_REGISTRY_IMAGE:cache"
      --platform linux/amd64,linux/arm64
      -t "${CI_REGISTRY_IMAGE}:latest"
      . --push
  tags:
    - docker
    - amd64
